---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    downloads_dir: /tmp/downloads
  tasks:
  - name: install apt packages
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
    - build-essential
    - curl
    - debootstrap
    - htop
    - tree
    - wget

  - name: ensure downloads directory exists
    file: path={{downloads_dir}} state=directory

  - name: download go
    get_url: url=https://storage.googleapis.com/golang/go1.8.3.linux-amd64.tar.gz dest={{downloads_dir}}/go.tar.gz

  - name: extract go
    unarchive: copy=no src={{downloads_dir}}/go.tar.gz dest=/usr/local creates=/usr/local/go

  - lineinfile:
      path: ~/.bashrc
      line: 'export PATH=/usr/local/go/bin:$PATH'
