#!/usr/bin/env bash
set -euo pipefail

if [ ! -d ~/rootfs/stretch ]; then
  mkdir -p ~/rootfs/stretch
  debootstrap --include stress stretch ~/rootfs/stretch
fi

if ! which ginkgo >/dev/null 2>&1; then
  (
  cd ~
  go get -v github.com/onsi/ginkgo/ginkgo
  )
fi

ginkgo -r -p -nodes 8 -randomizeAllSpecs -randomizeSuites "$@"
